<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-11-03 18:14

$extensionPath = t3lib_extMgm::extPath('less');
$extensionClassesPath = t3lib_extMgm::extPath('less') . 'Classes/';
return array(
	'tx_less_configuration_beregistry' => $extensionClassesPath . 'Configuration/BeRegistry.php',
	'tx_less_hooks_t3libpagerendererrenderpreprocesshook' => $extensionClassesPath . 'Hooks/T3libPageRendererRenderPreProcessHook.php',
	'tx_less_less_parserfactory' => $extensionClassesPath . 'Less/ParserFactory.php',
	'tx_less_less_parserwrapper' => $extensionClassesPath . 'Less/ParserWrapper.php',
);
?>